### PR TITLE
Revert "fix: do not show wildcard hosts"

### PR DESCRIPTION
**Pull request by sunlei**
Reverts sunlei/zsh-ssh#6

### CODE REVIEW

**Comment by Shourai** [comment]
Did the previous change not work for you?

**Comment by sunlei** [comment]
Yes, I am using `awk` on macOS.
I think we need to find a way to be compatible at the same time, because not everyone will install `gwak`.

**Comment by sunlei** [comment]
try https://github.com/sunlei/zsh-ssh/commit/c1a07b7a0ff891dbe7d88acd6641a6db977c4b23

**Comment by Shourai** [comment]
Your fix works for me, thanks!

**Pull request merged**
